route:
  receiver: local-demonstration-sink
  group_by: [alertname]
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 4h

receivers:
  - name: local-demonstration-sink
    webhook_configs:
      - url: http://alert-sink:5001/alerts
        send_resolved: true

